name: CI

on:
  pull_request:
    branches:
      - master
  push:
      branches-ignore:
        - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
      with:
        ref: ${{ github.ref }}
    - name: Set up Python 3.x
      uses: actions/setup-python@main
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black pylint
    - name: Lint
      run: |
        black --check --diff places.py
        pylint pylint -d C0114,E0401 --persistent=n places.py
